# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 06:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Matchup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('playoff', models.IntegerField()),
                ('score', models.IntegerField()),
                ('opponent_score', models.IntegerField()),
                ('result', models.CharField(max_length=4)),
                ('at_home', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Player')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('sub_id', models.IntegerField()),
                ('buy_in', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='record',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Season'),
        ),
        migrations.AddField(
            model_name='payout',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Player'),
        ),
        migrations.AddField(
            model_name='payout',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Season'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager', to='leaguehistory.Player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='opponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent', to='leaguehistory.Player'),
        ),
        migrations.AddField(
            model_name='matchup',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Season'),
        ),
    ]
