# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-02 05:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaguehistory', '0002_season_sub_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchup',
            name='playoff_round',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
