# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-19 03:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leaguehistory', '0003_matchup_playoff_round'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wins', models.IntegerField()),
                ('losses', models.IntegerField()),
                ('ties', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='leaguehistory.Season')),
            ],
        ),
    ]
