# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-04 07:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leaguehistory', '0004_standings'),
    ]

    operations = [
        migrations.RenameModel('Standings', 'Record')
    ]
